spring:
  config:
    activate:
      on-profile: local
  jpa:
    database: h2
    show-sql: 'true'
    open-in-view: 'false'
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    hikari:
      maximum-pool-size: '10'
    username: sa
    url: jdbc:h2:~/shop
  h2:
    console:
      path: /h2-console
      enabled: 'true'
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always
logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      myshop: DEBUG
    root: INFO


